name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32.1

    - name: Test
      run: go test -a -v -timeout 1m ./...

    - name: Build
      run: go build -v ./...

