on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: "https://golang.org/dl/go1.16.linux-amd64.tar.gz"
        project_path: ./cmd/bspm
        binary_name: bspm
        ldflags: "-s -w -X 'main.Version=${{ github.event.release.tag_name }}'"
